### ISSUE TITLE
Hyperlink jump DO NOT generate correctly

### ISSUE THREAD

**Issue by irorange27** [LuminolT/SHU-OS-Lab-Report-Template#1]
OS: windows 11
I was used compile chain with **xelatex->bibtex->xelatex*2** in **vscode**.
And my distribution is **Tex Live 2023** just installed with tutorial.
Don't generate as same as sample and **compiler tells me** such information:
~~~
I found no \bibdata command
I found no \bibstyle command
I found no \citation commands
~~~

what should I do?

**Comment by LuminolT** [comment]
That's sounds like something went wrong with bib backend.

Try to add `bibend=bibtex` compile option. That may help you.

```tex
\documentclass[lang=cn,a4paper,chinesefont=founder,bibend=bibtex]{shu-lab-report}
```
